/**
 * 열고닫기 OPCL 웹후크 키 매핑 파일 (클라이언트용)
 * 
 * [주의] 
 * 이 파일은 브라우저로 전송되는 클라이언트 번들에 포함됩니다.
 * 실제 URL을 노출하지 않고, API 라우터(/api/webhook)에서 실제 주소와 매핑할 식별자(Key)만 제공합니다.
 */

export const WEBHOOK_URLS = {
  // 1단계: 인증 및 기본 정보
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  UPDATE_USER: "UPDATE_USER",

  // 2단계: 상담 신청
  SUBMIT_INTAKE: "SUBMIT_INTAKE",
  GET_CALENDAR: "GET_CALENDAR",
  CHOOSE_SCHEDULE: "CHOOSE_SCHEDULE",
  AI_CHAT_INPUT: "AI_CHAT_INPUT",
  AI_CHAT_ANALYZE: "AI_CHAT_ANALYZE",
  CONSENT_COMPLETE: "CONSENT_COMPLETE",

  // 3단계: 매니저 대시보드
  GET_MANAGER_DASHBOARD: "GET_MANAGER_DASHBOARD",
  GET_DASHBOARD_PREVIEW: "GET_DASHBOARD_PREVIEW",
  GET_COMPLETED_LIST: "GET_COMPLETED_LIST",
  ADJUST_SCHEDULE: "ADJUST_SCHEDULE",
  START_CONSULTATION: "START_CONSULTATION",
  CONSULTATION_SUMMARY: "CONSULTATION_SUMMARY",
  SUBMIT_FINAL_REPORT: "SUBMIT_FINAL_REPORT",
  CHECK_CASE: "CHECK_CASE",

  // 기타
  GET_DASHBOARD_APPLICATIONS: "GET_DASHBOARD_APPLICATIONS",
  GET_APPLICATION_DETAIL: "GET_APPLICATION_DETAIL",
  GET_COMPLETED_DETAIL: "GET_COMPLETED_DETAIL",
  GET_REPORT_EXAMPLE: "GET_REPORT_EXAMPLE",
  SYNC_GOOGLE_SHEETS: "SYNC_GOOGLE_SHEETS",
  GENERATE_NOTION_REPORT: "GENERATE_NOTION_REPORT",
};
